version: '3'
services:
  bd:
   build:
    context: ./BD
    dockerfile: Dockerfile
   image: localhost:5000/bd
   network_mode: "host"
   expose:
     - "5432"

  apigateway:
   build:
    context: ./Microservicios/apigateway
    dockerfile: Dockerfile
   image: localhost:5000/apigateway
   network_mode: "host"
   depends_on:
    - servicediscovery

  authserver:
   build:
    context: ./Microservicios/authserver
    dockerfile: Dockerfile
   image: localhost:5000/authserver
   network_mode: "host"
   depends_on:
    - apigateway

  servicediscovery:
   build:
    context: ./Microservicios/servicediscovery
    dockerfile: Dockerfile
   image: localhost:5000/servicediscovery
   network_mode: "host"
   depends_on:
    - bd

  usermanagement:
   build:
    context: ./Microservicios/usermanagement
    dockerfile: Dockerfile
   image: localhost:5000/usermanagement
   network_mode: "host"
   depends_on:
    - authserver
