apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2019-05-26T08:50:52Z"
  labels:
    app: prometheus-adapter
    chart: prometheus-adapter-1.0.2
    heritage: Tiller
    release: prometheus-adapter
  name: prometheus-adapter-external-metrics
  resourceVersion: "1981"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/prometheus-adapter-external-metrics
  uid: 5e03f936-7f93-11e9-8694-0800272fd834
rules:
- apiGroups:
  - external.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - list
  - get
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2019-05-26T08:50:52Z"
  labels:
    app: prometheus-adapter
    chart: prometheus-adapter-1.0.2
    heritage: Tiller
    release: prometheus-adapter
  name: prometheus-adapter-resource-reader
  resourceVersion: "1980"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/prometheus-adapter-resource-reader
  uid: 5dffc262-7f93-11e9-8694-0800272fd834
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  - configmaps
  verbs:
  - get
  - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2019-05-26T08:50:52Z"
  labels:
    app: prometheus-adapter
    chart: prometheus-adapter-1.0.2
    heritage: Tiller
    release: prometheus-adapter
  name: prometheus-adapter-server-resources
  resourceVersion: "1979"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/prometheus-adapter-server-resources
  uid: 5df8aa03-7f93-11e9-8694-0800272fd834
rules:
- apiGroups:
  - custom.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - '*'

