apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2019-05-26T08:50:52Z"
  labels:
    app: prometheus-adapter
    chart: prometheus-adapter-1.0.2
    heritage: Tiller
    release: prometheus-adapter
  name: prometheus-adapter-server-resources
  resourceVersion: "1979"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/prometheus-adapter-server-resources
  uid: 5df8aa03-7f93-11e9-8694-0800272fd834
rules:
- apiGroups:
  - custom.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
