apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2019-05-26T08:50:52Z"
  labels:
    app: prometheus-adapter
    chart: prometheus-adapter-1.0.2
    heritage: Tiller
    release: prometheus-adapter
  name: prometheus-adapter:system:auth-delegator
  resourceVersion: "1983"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/prometheus-adapter%3Asystem%3Aauth-delegator
  uid: 5e0e1045-7f93-11e9-8694-0800272fd834
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: prometheus-adapter
  namespace: kube-system
