apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2019-05-26T08:50:52Z"
  labels:
    app: prometheus-adapter
    chart: prometheus-adapter-1.0.2
    heritage: Tiller
    release: prometheus-adapter
  name: prometheus-adapter:system:auth-delegator
  resourceVersion: "1983"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/prometheus-adapter%3Asystem%3Aauth-delegator
  uid: 5e0e1045-7f93-11e9-8694-0800272fd834
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: prometheus-adapter
  namespace: kube-system

---

piVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2019-05-26T08:50:52Z"
  labels:
    app: prometheus-adapter
    chart: prometheus-adapter-1.0.2
    heritage: Tiller
    release: prometheus-adapter
  name: prometheus-adapter-hpa-controller-external-metrics
  resourceVersion: "1987"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/prometheus-adapter-hpa-controller-external-metrics
  uid: 5e1c5adb-7f93-11e9-8694-0800272fd834
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-adapter-external-metrics
subjects:
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2019-05-26T08:50:52Z"
  labels:
    app: prometheus-adapter
    chart: prometheus-adapter-1.0.2
    heritage: Tiller
    release: prometheus-adapter
  name: prometheus-adapter-hpa-controller
  resourceVersion: "1986"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/prometheus-adapter-hpa-controller
  uid: 5e181f2f-7f93-11e9-8694-0800272fd834
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-adapter-server-resources
subjects:
- kind: ServiceAccount
  name: prometheus-adapter
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2019-05-26T08:50:52Z"
  labels:
    app: prometheus-adapter
    chart: prometheus-adapter-1.0.2
    heritage: Tiller
    release: prometheus-adapter
  name: prometheus-adapter-resource-reader
  resourceVersion: "1984"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/prometheus-adapter-resource-reader
  uid: 5e13f7fa-7f93-11e9-8694-0800272fd834
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-adapter-resource-reader
subjects:
- kind: ServiceAccount
  name: prometheus-adapter
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2019-05-26T08:50:52Z"
  labels:
    app: prometheus-adapter
    chart: prometheus-adapter-1.0.2
    heritage: Tiller
    release: prometheus-adapter
  name: prometheus-adapter-auth-reader
  namespace: kube-system
  resourceVersion: "1988"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/prometheus-adapter-auth-reader
  uid: 5e20ad91-7f93-11e9-8694-0800272fd834
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: prometheus-adapter
  namespace: kube-system
