apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2019-05-26T08:50:52Z"
  labels:
    app: prometheus-adapter
    chart: prometheus-adapter-1.0.2
    heritage: Tiller
    release: prometheus-adapter
  name: prometheus-adapter-hpa-controller-external-metrics
  resourceVersion: "1987"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/prometheus-adapter-hpa-controller-external-metrics
  uid: 5e1c5adb-7f93-11e9-8694-0800272fd834
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-adapter-external-metrics
subjects:
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: kube-system
