apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: app1-container
        image: app1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 400m

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: app2-container
        image: app2
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 400m

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
spec:
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: app3-container
        image: app3
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        resources:
          requests:
            cpu: 50m
