---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: app1-hpa
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: app1
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: fs_io_current
      targetAverageValue: 10

---

# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: app2-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: extensions/v1beta1
#     kind: Deployment
#     name: app2
#   minReplicas: 2
#   maxReplicas: 10
#   metrics:
#   - type: Object
#     object:
#       target:
#         kind: Service
#         name: app2
#       metricName: http_requests
#       targetValue: 100
